## Sales Effectiveness Analysis and Lead Potential Prediction

### Project Introduction

Sales Effectiveness Analysis and Lead Potential Prediction

This project focuses on analyzing sales lead data to identify the key factors that influence sales effectiveness and lead conversion.The analysis includes data cleaning, exploratory data analysis, visualization, feature engineering, and machine learning.

The objective is to generate meaningful business insightss and develop a machine learning model that can help identify high-potential leads, and improve overall sales performance.

### Project Workflow

1.Project Introduction
2.Importing Libraries
3.Loading the Dataset
4.Data Understanding
5.Data Cleaning & Preprocessing
6.Exploratory Data Analysis
7.Feature Engineering
8.Target Variable Prepration
9.Feature Encoding & Preparation
10.Train-Test Split
11.Machine Learning Model Building
12.Model Evaluation
13.Model Comparison
14.Feature Importance
15.Business Insights & Recommendations
16.Final Conclusion

## Importing Required Libraries

In [1]:
# Main objective is to understand more about data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully")

Libraries imported successfully

## Loading the Dataset

In [2]:
# Load the Dataset

df = pd.read_csv("project_sales_data.csv", sep = ";", encoding = 'latin1')
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
# Display first five rows
df.head()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,14-11-2018 10:05,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,NaN,Mode-5,Open
1,14-11-2018 09:22,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
2,14-11-2018 09:21,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,NaN,Mode-5,Open
3,14-11-2018 08:46,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
4,14-11-2018 07:34,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open

In [4]:
df.tail()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
7417,28-04-2018 09:45,9.0,Call,NaN,aXXXXXXX@gmail.com,Sales-Agent-6,Mumbai,Mode-4,LOST
7418,28-04-2018 09:43,15.0,Call,NaN,#VALUE!,Sales-Agent-12,Other Locations,Mode-5,LOST
7419,28-04-2018 09:20,5.0,Live Chat-Direct,NaN,sXXXXXXX@gmail.com,Sales-Agent-11,Bangalore,Mode-1,Not Responding
7420,28-04-2018 08:04,21.0,CRM form,NaN,YXXXXXXX@gmail.com,Sales-Agent-4,Other Locations,Mode-1,Just Enquiry
7421,28-04-2018 07:54,25.0,Website,NaN,cXXXXXXX@gmail.com,Sales-Agent-3,Chennai,Mode-1,CONVERTED

In [5]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7422 entries, 0 to 7421
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Created        7422 non-null   object
 1   Product_ID     7364 non-null   float64
 2   Source         7405 non-null   object
 3   Mobile         5612 non-null   object
 4   EMAIL          7422 non-null   object
 5   Sales_Agent    7399 non-null   object
 6   Location       7364 non-null   object
 7   Delivery_Mode  7422 non-null   object
 8   Status         7422 non-null   object
dtypes: float64(1), object(8)
memory usage: 522.0+ KB

In [6]:
# Checking dataset shape
print("Dataset Shape :", df.shape)

Dataset Shape : (7422, 9)

## Understanding the Dataset

After loading the dataset, the next step is to assess its overall data quality. This includes identifying missing values across the available features.
Detecting missing data at an early stage helps determine the appropriate data-cleaning and preprocessing techniques requried for further analysis.

In [7]:
# Checking the missing values in each column

df.isnull().sum()

Created             0
Product_ID         58
Source             17
Mobile           1810
EMAIL               0
Sales_Agent        23
Location           58
Delivery_Mode       0
Status              0
dtype: int64

## Observation
The Mobile column has the highest number of missing values.

## Checking Duplicate Records

Duplicate records can occur when the same information is entered or recorded more then once. Identifying duplicate observations is an important step in data preprocessing, as duplicates may affect the accuracy of analysis and subsequent modeling.

In [8]:
# Checking the duplicate records

df.duplicated().sum()

np.int64(2)

# Observation
In the dataset, there are 2 duplicate rows.

## Inspecting Duplicate Records

After identifying duplicate records, the next step is to examine the duplicated rows in detail. This helps verify whether the records are exact duplicates and ensures that only unnecessary duplicate entries are removed during data cleaning.

In [9]:
# Displaying duplicates records

df[df.duplicated(keep=False)]

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
129,10-11-2018 20:27,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
130,10-11-2018 20:27,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
134,10-11-2018 20:17,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
135,10-11-2018 20:17,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open

## Removing Duplicate Records

After inspecting the duplicate records, the next step is to remove the reduntant entries from the dataset. Removing duplicate records helps maintain data consistency.

In [10]:
# Removing duplicate records
df = df.drop_duplicates()

print("Duplicate records removed successfully!")

Duplicate records removed successfully!

In [11]:
# Checking the number of duplicate records after removal
print("Remaining duplicate records :",df.duplicated().sum())

Remaining duplicate records : 0

# Observation
Duplicate records removed successfully from the dataset.

## Handling Missing Values

Missing values are common in real-world datasets and may occur due to incomplete or unavailable information. Before performing further analysis, it is important to identify the missing values and understand their distribution across different columns.

#### Checking Missing Values

In [12]:
# Checking missing values in each column
missing_values = df.isnull().sum()

print("Missing values in each column :")
print(missing_values)

Missing values in each column :
Created             0
Product_ID         56
Source             17
Mobile           1810
EMAIL               0
Sales_Agent        23
Location           56
Delivery_Mode       0
Status              0
dtype: int64

#### Calculaing missing-value percentage

In [13]:
## Calculating the percentage of missing values
missing_percentage = (df.isnull().sum() /len(df))*100

print("Missing Value percentage :")
print(missing_percentage.round(2))

Missing Value percentage :
Created           0.00
Product_ID        0.75
Source            0.23
Mobile           24.39
EMAIL             0.00
Sales_Agent       0.31
Location          0.75
Delivery_Mode     0.00
Status            0.00
dtype: float64

#### Identifying Columns with Missing Values

After calculating the percentage of missing values, the next step is to identify the columns containing missing data. This helps us determine which columns require treatment.

In [14]:
# Identifying columns with missing values
missing_columns = df.columns[df.isnull().any()]

print("Columns containing missing values :")
print(missing_columns)

Columns containing missing values :
Index(['Product_ID', 'Source', 'Mobile', 'Sales_Agent', 'Location'], dtype='object')

## Understanding Product_ID

The Product_ID column represents the products associated with each sales lead. Before handling its missing values, it is important to examine the available product identifiers and their frequnecy.This helps determine whether the missing values can be reasonably handled.

### Checking the Unqiue Product IDS

In [15]:
# Checking unique Product IDS
df['Product_ID'].unique()

array([nan,  9., 19., 18., 15., 27.,  5.,  2.,  3., 25., 10., 20., 11.,
       21.,  1., 12., 13., 17., 24., 26., 16., 23., 22.,  8., 14.,  6.,
        0., 28.,  7.,  4.])

# Observation
. 56 missing values
. Product_IDs from 0 to 28
. The IDs are numeric, so product_Id is being treated as a numerical column.

#### Product ID Frequency

To understand the distribution of products in the dataset, the frequency of each Product ID is examined. This analysis helps identify the most frequently occurring products and supports an appropriate strategy for handling missing Product ID values.

In [16]:
# Checking the frequency of each Product ID
df['Product_ID'].value_counts(dropna = False)

Product_ID
18.0    1711
15.0    1518
19.0    1189
9.0      992
27.0     739
5.0      487
10.0     168
1.0      105
20.0     102
25.0      90
21.0      66
NaN       56
2.0       38
12.0      36
26.0      31
14.0      27
11.0      12
22.0       8
3.0        7
6.0        7
17.0       7
8.0        6
13.0       5
24.0       3
16.0       3
23.0       2
0.0        2
28.0       1
7.0        1
4.0        1
Name: count, dtype: int64

# Observation
The product_ID column contains 56 missing values. Product Id 18 is the most frequently occuring product, with 1,711 records.Since the missing product
IDs cannot be reliably determined from frequency alone, they should not be replaced with the most frequent Product ID.

#### Handling Missing Product_Id Values

The records with missing Product IDs are examined using the available information in other columns.This helps determine whether the missing product identifiers can be inferred from related fields or whether they should be retained as unknown values

In [17]:
# Displaying records with missing Product_ID
df[df['Product_ID'].isnull()]

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,14-11-2018 10:05,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,NaN,Mode-5,Open
1,14-11-2018 09:22,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
2,14-11-2018 09:21,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,NaN,Mode-5,Open
3,14-11-2018 08:46,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
4,14-11-2018 07:34,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
5,14-11-2018 07:33,NaN,Website,XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
6,14-11-2018 05:58,NaN,Website,XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
7,14-11-2018 05:49,NaN,Website,XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
8,14-11-2018 05:40,NaN,Website,078XXXXXXX,DXXXXXXXheblue.com,Sales-Agent-10,NaN,Mode-5,Open
9,14-11-2018 05:06,NaN,Website,XXXXXXX,jXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
10,14-11-2018 05:03,NaN,Website,XXXXXXX,dXXXXXXXt9@aol.com,Sales-Agent-10,NaN,Mode-5,Open
11,14-11-2018 04:52,NaN,Website,XXXXXXX,eXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
12,14-11-2018 02:37,NaN,Website,467XXXXXXX,bXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
13,13-11-2018 23:40,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
14,13-11-2018 21:14,NaN,Website,984XXXXXXX,SXXXXXXXutlook.com,Sales-Agent-10,NaN,Mode-5,Open
15,13-11-2018 20:45,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
16,13-11-2018 20:15,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
17,13-11-2018 20:14,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
20,13-11-2018 18:41,NaN,Website,04.XXXXXXX,WXXXXXXXlowpol.com,Sales-Agent-10,NaN,Mode-5,Open
21,13-11-2018 18:25,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
22,13-11-2018 18:03,NaN,Website,805XXXXXXX,eXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
23,13-11-2018 17:25,NaN,Call,+96XXXXXXX,hXXXXXXX@gmail.com,Sales-Agent-9,UAE,Mode-3,In Progress Positive
126,10-11-2018 22:34,NaN,Website,988XXXXXXX,VXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
127,10-11-2018 21:41,NaN,Website,719XXXXXXX,AXXXXXXXheblue.com,Sales-Agent-10,NaN,Mode-5,Open
128,10-11-2018 20:40,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
129,10-11-2018 20:27,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
131,10-11-2018 20:25,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
132,10-11-2018 20:20,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
133,10-11-2018 20:19,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
134,10-11-2018 20:17,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
136,10-11-2018 19:39,NaN,Website,932XXXXXXX,CXXXXXXX@yahoo.com,Sales-Agent-10,NaN,Mode-5,Open
137,10-11-2018 19:13,NaN,Website,999XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
138,10-11-2018 18:00,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
1888,17-09-2018 18:55,NaN,Live Chat-Direct,704XXXXXXX,aXXXXXXX4@nitie.ac,Sales-Agent-5,Mumbai,Mode-3,Junk Lead
2487,31-08-2018 22:31,NaN,Website,704XXXXXXX,pXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
2488,31-08-2018 21:26,NaN,Website,932XXXXXXX,pXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
2489,31-08-2018 20:34,NaN,Website,01.XXXXXXX,mXXXXXXXaskpsi.com,Sales-Agent-10,NaN,Mode-5,Open
2556,29-08-2018 19:41,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
2726,24-08-2018 15:20,NaN,Website,735XXXXXXX,PXXXXXXXOTMAIL.COM,Sales-Agent-11,NaN,Mode-5,Just Enquiry
2727,24-08-2018 14:36,NaN,US Website,091XXXXXXX,hXXXXXXXailbox.com,Sales-Agent-5,NaN,Mode-5,Not Responding
2729,24-08-2018 13:50,NaN,US Website,077XXXXXXX,kXXXXXXXstabbi.com,Sales-Agent-11,NaN,Mode-5,Just Enquiry
3023,16-08-2018 12:08,NaN,Call,948XXXXXXX,#VALUE!,Sales-Agent-5,Other Locations,Mode-5,Junk Lead
3051,15-08-2018 21:44,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
3053,15-08-2018 20:36,NaN,Website,037XXXXXXX,bXXXXXXXieblog.com,Sales-Agent-10,NaN,Mode-5,Open
3061,14-08-2018 21:43,NaN,Website,893XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
3130,13-08-2018 16:59,NaN,Website,889XXXXXXX,tXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
3250,09-08-2018 18:26,NaN,Website,990XXXXXXX,dXXXXXXXllogic.com,Sales-Agent-10,NaN,Mode-5,Open
3384,06-08-2018 20:42,NaN,US Website,418XXXXXXX,sXXXXXXXamiami.com,Sales-Agent-10,NaN,Mode-5,Open
3740,28-07-2018 23:11,NaN,Website,919XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
3752,28-07-2018 12:25,NaN,Live Chat-Direct,974XXXXXXX,sXXXXXXX@yahoo.com,Sales-Agent-5,Other Locations,Mode-5,Just Enquiry
4979,25-06-2018 16:31,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
5086,22-06-2018 15:03,NaN,Website,916XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-4,Other Locations,Mode-3,Long Term
5235,19-06-2018 23:41,NaN,Website,975XXXXXXX,SXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
5258,19-06-2018 17:12,NaN,NaN,987XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
5549,12-06-2018 21:00,NaN,NaN,705XXXXXXX,jXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
5664,10-06-2018 11:12,NaN,US Website,NaN,vXXXXXXXaz@mail.ru,Sales-Agent-4,Other Locations,Mode-5,Not Responding

## Observation
Since the missing Product_ID values have already been quantified and inspected, the next step is to determine an appropriate treatment.
As Product_ID is an identifier, imputing an arbitrary product number could introduce inaccurate information. Therefore, we will preserve the missing values for now and ensures that they are handled appropriately during the modelling stage.

## Handling Missing source Values

The source column represents the channel through which the sales lead was generated. Since only a small proportion of records have missing values, we will first examine the available source categories and their frequency. This will help us determine an appropriate method for handling the missing values.

In [18]:
# Checking the frequency of each Source
df['Source'].value_counts(dropna = False)

Source
Call                             2547
Live Chat-Direct                 1834
Website                          1592
Live Chat-Google Organic          274
Live Chat -PPC                    249
Live Chat-Blog                    237
Customer Referral                 180
US Website                        137
Just Dial                          56
Existing Client                    51
Personal Contact                   50
Live Chat-CPC                      50
By Recommendation                  32
CRM form                           23
Existing Customer                  22
Live Chat-Google Ads               21
Campaign                           19
NaN                                17
E-mail Campaign                    12
Live Chat-Adwords Remarketing       7
Other                               2
Live Chat-Quora                     2
Live Chat-Youtube                   2
SMS Campaign                        2
E-Mail Message                      1
Live Chat-Justdial                  1
Name: count, dtype: int64

#### Inspecting Records with Missing Source

After examining the frequency of each source category, the next step is to inspect the records where Source is missing. This allows us to check whether other columns contain useful information that can help us understand or determine the missing source values.

In [19]:
# Displaying records with missing Source values
df[df['Source'].isnull()]

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
13,13-11-2018 23:40,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
15,13-11-2018 20:45,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
21,13-11-2018 18:25,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
128,10-11-2018 20:40,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
138,10-11-2018 18:00,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
2518,30-08-2018 20:40,18.0,NaN,961XXXXXXX,kXXXXXXXahoo.co.in,Sales-Agent-5,Other Locations,Mode-3,Not Responding
2556,29-08-2018 19:41,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
2686,26-08-2018 11:10,9.0,NaN,916XXXXXXX,dXXXXXXX@gmail.com,Sales-Agent-5,Mumbai,Mode-3,Just Enquiry
2712,25-08-2018 10:00,15.0,NaN,998XXXXXXX,sXXXXXXX@gmail.com,Sales-Agent-5,Mumbai,Mode-5,Junk Lead
2767,23-08-2018 14:40,15.0,NaN,995XXXXXXX,#VALUE!,Sales-Agent-11,Hyderabad,Mode-5,In Progress Negative
3051,15-08-2018 21:44,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
4979,25-06-2018 16:31,NaN,NaN,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
5258,19-06-2018 17:12,NaN,NaN,987XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
5549,12-06-2018 21:00,NaN,NaN,705XXXXXXX,jXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
6627,17-05-2018 14:45,9.0,NaN,NaN,gXXXXXXX@gmail.com,Sales-Agent-7,Bangalore,Mode-1,LOST
6886,10-05-2018 21:30,5.0,NaN,NaN,aXXXXXXX.j@pwc.com,Sales-Agent-11,Other Locations,Mode-1,Potential
6910,10-05-2018 14:10,18.0,NaN,NaN,PXXXXXXX@gmail.com,Sales-Agent-7,Chennai,Mode-1,Not Responding

#### Handling Missing source Values

Since the 17 missing Source values cannot be reliably determined from the available information, we will replace them with the category Unknown.The preserves all records while clearly indicating that the original source information was unavailable.

In [20]:
# Replacing missing Source values with 'Unknown'

df['Source'] = df['Source'].fillna('Unknown')

print("Missing Source values handled successfully!")

Missing Source values handled successfully!

#### Verifying missing Source values

##### Checking Missing Source Values After Handling

After replacing the missing values in the Source column with 'Unknown', we verify that no missing values remain in the column. This ensures that the missing Source values have been handled correctly.

In [21]:
# Checking missing Source values after handling

print("Remaining missing Source values :", df['Source'].isnull().sum())

Remaining missing Source values : 0

## Observation
The Source column contained 17 missing values. Since the orginal source information could not be raliably determined from the available data, the missing
values were replaced with "Unknown". After handling,the column was verified and confirmed to have 0 remaining missing values.

## Understanding Mobile

The Mobile column contains the moblie contact numbers associated with each sales lead. Before handling the missing values, we will inspect the frequency of the available mobile numbers and identify the number of missing entries. This will help us choose an appropriate data-cleaning strategy.

In [22]:
# Checking the frequency of Mobile values

df['Mobile'].value_counts(dropna = False).head(20)

Mobile
NaN           1810
XXXXXXX        220
988XXXXXXX     211
984XXXXXXX     177
998XXXXXXX     125
994XXXXXXX     112
990XXXXXXX     105
974XXXXXXX      97
996XXXXXXX      95
971XXXXXXX      90
991XXXXXXX      81
981XXXXXXX      80
973XXXXXXX      65
900XXXXXXX      64
999XXXXXXX      61
888XXXXXXX      61
989XXXXXXX      59
965XXXXXXX      56
953XXXXXXX      55
983XXXXXXX      53
Name: count, dtype: int64

#### Inspecting Records with Missing Mobile Values

To understand the missing Mobile values in detail, we will display the records where the Mobile column is missing. This allows us to examine other available information in those records before deciding how to handle the missing values.

In [23]:
# Displaying records with missing Mobile values

df[df['Mobile'].isnull()]

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
5612,11-06-2018 14:34,18.0,Call,NaN,nXXXXXXX@gmail.com,Sales-Agent-2,Bangalore,Mode-1,Junk Lead
5613,11-06-2018 13:49,27.0,Call,NaN,mXXXXXXX@gmail.com,Sales-Agent-11,Mumbai,Mode-3,Long Term
5614,11-06-2018 13:49,15.0,Call,NaN,#VALUE!,Sales-Agent-4,Other Locations,Mode-5,Not Responding
5615,11-06-2018 13:49,27.0,Call,NaN,fXXXXXXX@gmail.com,Sales-Agent-5,Other Locations,Mode-3,LOST
5616,11-06-2018 13:47,18.0,Call,NaN,#VALUE!,Sales-Agent-5,Other Locations,Mode-3,Just Enquiry
...,...,...,...,...,...,...,...,...,...
7417,28-04-2018 09:45,9.0,Call,NaN,aXXXXXXX@gmail.com,Sales-Agent-6,Mumbai,Mode-4,LOST
7418,28-04-2018 09:43,15.0,Call,NaN,#VALUE!,Sales-Agent-12,Other Locations,Mode-5,LOST
7419,28-04-2018 09:20,5.0,Live Chat-Direct,NaN,sXXXXXXX@gmail.com,Sales-Agent-11,Bangalore,Mode-1,Not Responding
7420,28-04-2018 08:04,21.0,CRM form,NaN,YXXXXXXX@gmail.com,Sales-Agent-4,Other Locations,Mode-1,Just Enquiry
7421,28-04-2018 07:54,25.0,Website,NaN,cXXXXXXX@gmail.com,Sales-Agent-3,Chennai,Mode-1,CONVERTED

## Observation
The Mobile column conatains 1,810 missing values. These missing values occur across records with different sources, sales agents, locations, and statuses. Since the original mobile numbers cannot be raliably determined from the available information, the missing values should not be replaced with guessed numbers. They will be handled using a suitable placeholder while preserving the remaining records.

#### Handling Missing Mobile Values

Since the actual Mobile numbers are unavailable for these records, we will replace the missing values with 'Not Available'. This keeps the records in the dataset and clearly indicates that the mobile number was not provided.

In [24]:
# Replacing missing Mobile values with 'Not Available'

df['Mobile'] = df['Mobile'].fillna("Not Available")

print("Missing values handled successfully!")

Missing values handled successfully!

#### Verifying Missing Mobile Values

After replacing the missing values in the Mobile column with 'Not Available', we will verify that no missing values remain. This ensures that all missing Mobile values have been handled correctly before moving to the next column.

In [25]:
# Checking missing Mobile values after handling

print("Remaining missing Mobile values :", df['Mobile'].isnull().sum())

Remaining missing Mobile values : 0

## Observation
The Mobile column initially contained 1,810 missing values. Since the actual mobile numbers could not be raliably determined, the missing values were replaced with 'Not Available'. After handling, the verification confirmed that 0 missing values remain, ensuring the Mobile column is complete for further analysis.

## Understanding Missing Sales_Agent Values

The Sales_Agent column contains the sales representative assigned to each record. We will first examine the frequency of each Sales_Agent value, including missing values, to understand the extent of missing data before deciding how to handle it.

In [26]:
# Checking the frequency of each Sales_Agent value

df['Sales_Agent'].value_counts(dropna = False)

Sales_Agent
Sales-Agent-4     1500
Sales-Agent-11    1420
Sales-Agent-5     1190
Sales-Agent-9      879
Sales-Agent-3      781
Sales-Agent-7      736
Sales-Agent-2      389
Sales-Agent-12     269
Sales-Agent-6      114
Sales-Agent-8       68
Sales-Agent-10      47
NaN                 23
Sales-Agent-1        4
Name: count, dtype: int64

#### Inspecting those 23 records

##### Inspecting Records with Missing Sales_Agent Values

To understand the missing Sales_Agent values in detail, we will display the records where Sales_Agent is missing. This allows us to examine other available information and determine whether the missing sales agents can be reliably identified.

In [27]:
# Displaying records with missing Sales_Agent values

df[df['Sales_Agent'].isnull()]

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
118,11-11-2018 12:35,5.0,Live Chat-Google Ads,986XXXXXXX,AXXXXXXX@gmail.com,NaN,Other Locations,Mode-5,Open
593,25-10-2018 18:02,15.0,Live Chat-Direct,854XXXXXXX,sXXXXXXX@gmail.com,NaN,Other Locations,Mode-5,Open
651,24-10-2018 11:01,18.0,Website,987XXXXXXX,sXXXXXXX@gmail.com,NaN,Delhi,Mode-5,Just Enquiry
658,24-10-2018 10:18,17.0,Live Chat-Google Organic,XXXXXXX,rXXXXXXX@yahoo.com,NaN,UAE,Mode-3,Open
681,23-10-2018 12:09,15.0,Live Chat-Google Organic,XXXXXXX,sXXXXXXX@gmail.com,NaN,Other Locations,Mode-3,Open
690,23-10-2018 11:33,15.0,Call,904XXXXXXX,dXXXXXXX@yahoo.com,NaN,Other Locations,Mode-5,Open
691,23-10-2018 11:31,15.0,Call,903XXXXXXX,mXXXXXXX@gmail.com,NaN,Other Locations,Mode-5,Not Responding
884,16-10-2018 10:06,24.0,Call,952XXXXXXX,aXXXXXXX@gmail.com,NaN,Other Locations,Mode-1,Open
1109,09-10-2018 12:55,18.0,Live Chat-Direct,988XXXXXXX,yXXXXXXX@gmail.com,NaN,Bangalore,Mode-1,Potential
1490,27-09-2018 11:00,15.0,Call,776XXXXXXX,#VALUE!,NaN,Other Locations,Mode-5,Open
1734,21-09-2018 10:42,15.0,Call,831XXXXXXX,#VALUE!,NaN,Other Locations,Mode-5,Potential
2946,19-08-2018 14:00,19.0,Live Chat-Google Organic,803XXXXXXX,iXXXXXXXdomain.com,NaN,Bangalore,Mode-1,Just Enquiry
3987,22-07-2018 13:10,27.0,Live Chat-Direct,998XXXXXXX,aXXXXXXX@gmail.com,NaN,Other Locations,Mode-5,Open
4080,18-07-2018 18:10,15.0,Live Chat-CPC,816XXXXXXX,cXXXXXXX@gmail.com,NaN,Pune,Mode-1,Open
4229,15-07-2018 18:22,15.0,Website,986XXXXXXX,cXXXXXXX@gmail.com,NaN,Pune,Mode-5,Not Responding
4375,11-07-2018 14:22,15.0,Call,950XXXXXXX,#VALUE!,NaN,Other Locations,Mode-5,Not Responding
5321,18-06-2018 17:05,15.0,Live Chat-Google Organic,919XXXXXXX,hXXXXXXX@yahoo.com,NaN,Other Locations,Mode-2,Open
5780,07-06-2018 12:00,13.0,Call,Not Available,#VALUE!,NaN,Pune,Mode-5,Open
5784,07-06-2018 11:20,1.0,Live Chat-Direct,Not Available,mXXXXXXXu@live.com,NaN,Chennai,Mode-1,Open
5901,05-06-2018 09:51,15.0,Call,Not Available,#VALUE!,NaN,Other Locations,Mode-5,Open
6957,09-05-2018 12:45,5.0,Live Chat-Google Organic,Not Available,jXXXXXXX@gmail.com,NaN,Other Locations,Mode-4,Open
7099,05-05-2018 12:47,21.0,CRM form,Not Available,pXXXXXXXations.com,NaN,Bangalore,Mode-1,Just Enquiry
7101,05-05-2018 11:58,27.0,Call,Not Available,#VALUE!,NaN,Bangalore,Mode-1,Just Enquiry

# Observation
The Sales_Agent column contains 23 missing values.These missing values are spread across records with different sources, locations, and statuses. Since the orginal Sales Agent cannot be reliably determined from the available information, the missing values will be replaced wit a suitable placeholder while preserving the records for further analysis.

#### Handling Missing Sales_Agent Values

Since the correct Sales Agent cannot be reliably determined for these 23 records, we will replace the missing values with 'Not Available'. This clearly indicates that the Sales Agent information was not provided, without making up a value.

In [28]:
# Replacing the missing Sales_Agent values with 'Not Avaliable'

df['Sales_Agent'] = df['Sales_Agent'].fillna('Not Available')

print("Missing Sales_Agent values handled successfully!")

Missing Sales_Agent values handled successfully!

#### Verifying Missing Sales_Agent Values

After replacing the missing values with Not Available, we will check the Sales_Agent column again to confirm that no missing values remain.

In [29]:
# Checking missing Sales_Agent values after handling

print("Remaining missing Sales_Agent :", df['Sales_Agent'].isnull())

Remaining missing Sales_Agent : 0       False
1       False
2       False
3       False
4       False
        ...
7417    False
7418    False
7419    False
7420    False
7421    False
Name: Sales_Agent, Length: 7420, dtype: bool

# Observation
The Sales_Agent column initially contained 23 missing values. Since the actual Sales_Agent could not be raliably determined from the available information,the missing values were replaced with 'Not Available'.After handling,verification confirmed that 0 missing values remain.

## Understanding Missing Location Values

The Location column represents the location associated with each sales record. We will first check the frequency of each location, including missing values, so we can understand the missing data before deciding how to handle it.

In [30]:
# Checking the frequency of each Location value

df['Location'].value_counts(dropna = False)

Location
Other Locations    2500
Bangalore          2084
Chennai             909
Hyderabad           528
Delhi               471
Mumbai              402
Pune                142
UAE                  79
Trivandrum           58
NaN                  56
Kolkata              55
USA                  45
UK                   41
AUSTRALIA            25
Singapore            17
Malaysia              4
EUROPE                3
Howrah                1
Name: count, dtype: int64

#### Inspecting Records with Missing Location Values

To understand the missing Location values in detail, we will display the records where the Location column is missing. This allows us to examine the available information in these records before deciding how to handle the missing values.

In [31]:
# Displaying records with missing Location values

df[df['Location'].isnull()]

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,14-11-2018 10:05,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,NaN,Mode-5,Open
1,14-11-2018 09:22,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
2,14-11-2018 09:21,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,NaN,Mode-5,Open
3,14-11-2018 08:46,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
4,14-11-2018 07:34,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
5,14-11-2018 07:33,NaN,Website,XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
6,14-11-2018 05:58,NaN,Website,XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
7,14-11-2018 05:49,NaN,Website,XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
8,14-11-2018 05:40,NaN,Website,078XXXXXXX,DXXXXXXXheblue.com,Sales-Agent-10,NaN,Mode-5,Open
9,14-11-2018 05:06,NaN,Website,XXXXXXX,jXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
10,14-11-2018 05:03,NaN,Website,XXXXXXX,dXXXXXXXt9@aol.com,Sales-Agent-10,NaN,Mode-5,Open
11,14-11-2018 04:52,NaN,Website,XXXXXXX,eXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
12,14-11-2018 02:37,NaN,Website,467XXXXXXX,bXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
13,13-11-2018 23:40,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
14,13-11-2018 21:14,NaN,Website,984XXXXXXX,SXXXXXXXutlook.com,Sales-Agent-10,NaN,Mode-5,Open
15,13-11-2018 20:45,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
16,13-11-2018 20:15,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
17,13-11-2018 20:14,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
20,13-11-2018 18:41,NaN,Website,04.XXXXXXX,WXXXXXXXlowpol.com,Sales-Agent-10,NaN,Mode-5,Open
21,13-11-2018 18:25,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
22,13-11-2018 18:03,NaN,Website,805XXXXXXX,eXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
126,10-11-2018 22:34,NaN,Website,988XXXXXXX,VXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
127,10-11-2018 21:41,NaN,Website,719XXXXXXX,AXXXXXXXheblue.com,Sales-Agent-10,NaN,Mode-5,Open
128,10-11-2018 20:40,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
129,10-11-2018 20:27,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
131,10-11-2018 20:25,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
132,10-11-2018 20:20,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
133,10-11-2018 20:19,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
134,10-11-2018 20:17,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
136,10-11-2018 19:39,NaN,Website,932XXXXXXX,CXXXXXXX@yahoo.com,Sales-Agent-10,NaN,Mode-5,Open
137,10-11-2018 19:13,NaN,Website,999XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
138,10-11-2018 18:00,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-10,NaN,Mode-5,Open
2487,31-08-2018 22:31,NaN,Website,704XXXXXXX,pXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
2488,31-08-2018 21:26,NaN,Website,932XXXXXXX,pXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
2489,31-08-2018 20:34,NaN,Website,01.XXXXXXX,mXXXXXXXaskpsi.com,Sales-Agent-10,NaN,Mode-5,Open
2556,29-08-2018 19:41,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
2726,24-08-2018 15:20,NaN,Website,735XXXXXXX,PXXXXXXXOTMAIL.COM,Sales-Agent-11,NaN,Mode-5,Just Enquiry
2727,24-08-2018 14:36,NaN,US Website,091XXXXXXX,hXXXXXXXailbox.com,Sales-Agent-5,NaN,Mode-5,Not Responding
2729,24-08-2018 13:50,NaN,US Website,077XXXXXXX,kXXXXXXXstabbi.com,Sales-Agent-11,NaN,Mode-5,Just Enquiry
3051,15-08-2018 21:44,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
3053,15-08-2018 20:36,NaN,Website,037XXXXXXX,bXXXXXXXieblog.com,Sales-Agent-10,NaN,Mode-5,Open
3061,14-08-2018 21:43,NaN,Website,893XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
3130,13-08-2018 16:59,NaN,Website,889XXXXXXX,tXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
3250,09-08-2018 18:26,NaN,Website,990XXXXXXX,dXXXXXXXllogic.com,Sales-Agent-10,NaN,Mode-5,Open
3373,07-08-2018 11:19,15.0,US Website,819XXXXXXX,cXXXXXXXllania.com,Sales-Agent-4,NaN,Mode-5,Not Responding
3384,06-08-2018 20:42,NaN,US Website,418XXXXXXX,sXXXXXXXamiami.com,Sales-Agent-10,NaN,Mode-5,Open
3435,06-08-2018 00:39,18.0,US Website,+26XXXXXXX,bXXXXXXXahoo.co.uk,Sales-Agent-5,NaN,Mode-5,Long Term
3740,28-07-2018 23:11,NaN,Website,919XXXXXXX,rXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
4461,09-07-2018 14:05,20.0,Live Chat-Direct,903XXXXXXX,mXXXXXXX@gmail.com,Sales-Agent-4,NaN,Mode-5,Not Responding
4979,25-06-2018 16:31,NaN,Unknown,XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
5235,19-06-2018 23:41,NaN,Website,975XXXXXXX,SXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
5258,19-06-2018 17:12,NaN,Unknown,987XXXXXXX,#VALUE!,Sales-Agent-1,NaN,Mode-5,Open
5549,12-06-2018 21:00,NaN,Unknown,705XXXXXXX,jXXXXXXX@gmail.com,Sales-Agent-10,NaN,Mode-5,Open
5917,04-06-2018 22:32,15.0,Website,Not Available,jXXXXXXXvenirs.com,Sales-Agent-4,NaN,Mode-1,Not Responding
7001,08-05-2018 12:05,15.0,US Website,Not Available,#VALUE!,Sales-Agent-11,NaN,Mode-1,Just Enquiry
7301,01-05-2018 11:05,15.0,US Website,Not Available,wXXXXXXXinting.com,Sales-Agent-3,NaN,Mode-1,Junk Lead

# Observation
A total of 56 records were identified with missing values in the Location column. These records were displayed to examine the missing entries before applying an appropriate missing-value treatment.

#### Handling Missing Location Values

The Location column contains 56 missing values. Since the actual location cannot be determined reliably from the available data, these missing entries will be replaced with 'Not Available'. This preserves all records without introducing an assumed location.

In [32]:
# Replacing missing Location values with 'Not Available'

df['Location'] = df['Location'].fillna('Not Available')

print("Missing Location Values Handled Successfully!")

Missing Location Values Handled Successfully!

#### Verifying Missing Location Values

After replacing the missing values in the Location column with 'Not Available',we will verify that no missing values remain. This ensures that the Location column has been handled correctly before proceeding with further data cleaning and analysis.

In [33]:
# Checking missing Location values after handling

print("Remaining missing Location values :", df['Location'].isnull().sum())

Remaining missing Location values : 0

# Observation
The Location column initially contained 56 missing values. Since the exact location information could not be reliably determined, the missing values were replaced with 'Not Available'.After handling verification confirmed that 0 missing values remain.

### Final Verification of Missing Values

After handling the missing values in all identified columns, we will perform a final check across the entire dataset. This helps confirm whether any missing values are still present in any column before we proceed to the next stage of data cleaning.

In [34]:
# Checking missing values across the entire dataset

missing_values = df.isnull().sum()
print(missing_values)

Created           0
Product_ID       56
Source            0
Mobile            0
EMAIL             0
Sales_Agent       0
Location          0
Delivery_Mode     0
Status            0
dtype: int64

# Observation
After handling the identified missing values, all column except Product_ID contain no missing values. The 56 missing Product_ID values are intentionally retained because the actual product IDs cannot be reliably determined. These values will be considered later during preprocessing/model development if requried.

In [35]:
df.head()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,14-11-2018 10:05,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,Not Available,Mode-5,Open
1,14-11-2018 09:22,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,Not Available,Mode-5,Open
2,14-11-2018 09:21,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,Not Available,Mode-5,Open
3,14-11-2018 08:46,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,Not Available,Mode-5,Open
4,14-11-2018 07:34,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,Not Available,Mode-5,Open

### Checking Data Types

In this step, we will examine the data types of all columns to ensure that each variable is stored in appropriate format. Correct data types are important for accurate analysis and further preprocessing.

In [36]:
# Checking the data types of all columns
df.dtypes

Created           object
Product_ID       float64
Source            object
Mobile            object
EMAIL             object
Sales_Agent       object
Location          object
Delivery_Mode     object
Status            object
dtype: object

# Observation
The dataset contains both numerical and categorical columns. The created column is currently stored as an object and will need to be converted into a proper datetime format for time-based analysis. Product_ID is stored as float64 because it contains missing values. The remaining columns are stored as object data types and will be handled appropriately during preprocessing.

## Converting Created Column to DateTime

The Created column contains date and time information but is currently stored as an object data type. Converting it to DateTime will allow us to correctly perform date-based analysis and extract useful features such as day, month, year, and time.

In [37]:
# Converting Created column from object to datetime
df['Created'] = pd.to_datetime(df['Created'],dayfirst = True, errors = 'coerce')

print('Created column converted to datetime successfully!')

Created column converted to datetime successfully!

#### Verifying the Created Column

After converting the Created column to datetime format, we verify the conversion by checking its data type.This ensures that the column is correctly prepared for further date-based analysis and feature extraction.

In [38]:
# Verifying the data type of the Created column
print(df['Created'].dtype)

datetime64[ns]

In [39]:
df.head()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status
0,2018-11-14 10:05:00,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,Not Available,Mode-5,Open
1,2018-11-14 09:22:00,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,Not Available,Mode-5,Open
2,2018-11-14 09:21:00,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,Not Available,Mode-5,Open
3,2018-11-14 08:46:00,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,Not Available,Mode-5,Open
4,2018-11-14 07:34:00,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,Not Available,Mode-5,Open

# Observation
The Created column has been successfully converted from object to datetime format. This allows us to perform time-based analysis and extract useful information such as year,month,day,andtime.

## Exploratory Data Analysis(EDA)

Our first EDA step will be to understand the distribution of the Sales Lead Status column. This help us understand how the leads are currently categorized and which statuses occur most frequently in the sales data.

In [40]:
# Checking the distribution of Sales Lead Status
df['Status'].value_counts()

Status
Junk Lead               1536
Not Responding          1129
CONVERTED                834
Just Enquiry             760
Potential                708
Long Term                646
In Progress Positive     643
In Progress Negative     626
LOST                     440
Open                      80
converted                 18
Name: count, dtype: int64

# Observation
The dataset contains multiples sales lead statuses, with Junk Lead being the most frequent category(1,536 records), followed by Not Responding(1,129 records).Open has the lowest number of records (80),while CONVERTED and converted appear as separate categories due to diffrences in capitalization.

## Distribution of Lead Sources

In this step, we will analyze the Source column to understand where the sales leads are coming from. This helps us identify the most common lead-generation channels and understand which sources contribute number of leads.

In [41]:
# Checking the distribution of Lead Sources
df['Source'].value_counts()

Source
Call                             2547
Live Chat-Direct                 1834
Website                          1592
Live Chat-Google Organic          274
Live Chat -PPC                    249
Live Chat-Blog                    237
Customer Referral                 180
US Website                        137
Just Dial                          56
Existing Client                    51
Personal Contact                   50
Live Chat-CPC                      50
By Recommendation                  32
CRM form                           23
Existing Customer                  22
Live Chat-Google Ads               21
Campaign                           19
Unknown                            17
E-mail Campaign                    12
Live Chat-Adwords Remarketing       7
Other                               2
Live Chat-Quora                     2
Live Chat-Youtube                   2
SMS Campaign                        2
E-Mail Message                      1
Live Chat-Justdial                  1
Name: count, dtype: int64

# Observation
The analysis shows that Call is the most common lead source,followed by Live Chat-Direct and Website. Thses three sources cntribute substantically more leads than the remaining channels,indicating that they are the primary sources of sales leads. Several other sources contribute comparatively fewer leads.

## Distribution of Sales_Agent

In this step, we will analyze the Sales_Agent column to understand how many leads are assigned to each sales agent. This helps us evaluate the distribution of workload across sales agents and identify agents handling a higher or lower number of leads.

In [42]:
# Checking the distribution of leads among Sales Agents
df['Sales_Agent'].value_counts()

Sales_Agent
Sales-Agent-4     1500
Sales-Agent-11    1420
Sales-Agent-5     1190
Sales-Agent-9      879
Sales-Agent-3      781
Sales-Agent-7      736
Sales-Agent-2      389
Sales-Agent-12     269
Sales-Agent-6      114
Sales-Agent-8       68
Sales-Agent-10      47
Not Available       23
Sales-Agent-1        4
Name: count, dtype: int64

# Observation
The distribution of leads across sales agents is uneven. Sales-Agent-4 handles the highest number of leads(1,500),followed by Sales-Agent-11(1,420) and Sales-Agent-5(1,190). In contrast, some agents handle considerably fewer leads, indicating differences in lead allocation across the sales team.

## Distribution of Location

In this step, we will analyze the Location column to understand across diffrent locations. This can help us identify the locations contributing the highest number of leads and understand the geographical distribution of the sales pipeline.

In [43]:
# Checking the distribution of leads by Location
df['Location'].value_counts()

Location
Other Locations    2500
Bangalore          2084
Chennai             909
Hyderabad           528
Delhi               471
Mumbai              402
Pune                142
UAE                  79
Trivandrum           58
Not Available        56
Kolkata              55
USA                  45
UK                   41
AUSTRALIA            25
Singapore            17
Malaysia              4
EUROPE                3
Howrah                1
Name: count, dtype: int64

# Obseervation
The lead distribution varies significantly across locations. Other Locations has the highest number of leads(2,500),followed by Bangalore(2,084) and Chennai(909).Hyderabad,Delhi,andMumbai contribute a moderate number of leads, while international locations and some smaller locations contribute relatively fewer leads.

## Distribution of Delivery Mode

In this step, we will analyze the Delivery_Mode column to understand how leads are distributed across different delivery modes. This helps us identify the most frequently used delivery methods within the sales dataset.

In [44]:
# Checking the distribution of leads by Delivery Mode
df['Delivery_Mode'].value_counts()

Delivery_Mode
Mode-5    2973
Mode-1    2627
Mode-3    1688
Mode-4     121
Mode-2      11
Name: count, dtype: int64

# Observation
The distribution of leads across delivery modes is highly uneven. Mode-5 has the highest number of leads (2,973),followed by Mode-1(2,627) and Mode-3(1,688). Mode-4 and Mode-2 account for comratively fewer leads, with Mode-2 having the lowest count of 11.

## Created Date analysis

Since we already converted Created to datetime, we can now examine when the leads were created. First, we'll determine the earliest and latest lead dates. This gives us the overall time period covered by the dataset.

In [45]:
# Checking the date range of sales leads
print("Earliest Lead Date :", df['Created'].min())
print("Latest Lead Date :", df['Created'].max())

Earliest Lead Date : 2018-04-28 07:54:00
Latest Lead Date : 2018-11-14 10:05:00

#### Monthly Lead Trend

Now that we know the dataset covers April 2018 to November 2018,we will examine how many leads were created in each month. This is more useful for business analysis because it helps us identify peroids with higher or lower lead generation.

In [46]:
# Checking the monthly distribution of sales leads
df['Created'].dt.to_period('M').value_counts().sort_index()

Created
2018-04     115
2018-05    1260
2018-06    1285
2018-07    1157
2018-08    1119
2018-09    1103
2018-10    1000
2018-11     381
Freq: M, Name: count, dtype: int64

## Source vs Sales Lead Status

In this step, we will analyze the relationship between Lead Source and Sales Lead Status. This will help us understand how leads from different sources are distributed across the various sales outcomes.

In [47]:
# Analyzing Lead Source against Sales Lead Status
pd.crosstab(df['Source'], df['Status'])

Status,CONVERTED,In Progress Negative,In Progress Positive,Junk Lead,Just Enquiry,LOST,Long Term,Not Responding,Open,Potential,converted
Source,,,,,,,,,,,
By Recommendation,18,0,1,0,0,1,4,2,1,5,0
CRM form,3,5,0,3,2,3,0,3,0,4,0
Call,240,200,213,730,217,159,215,308,16,248,1
Campaign,4,0,0,4,0,1,2,6,0,2,0
Customer Referral,118,4,15,4,4,2,5,5,0,21,2
E-Mail Message,0,0,0,0,0,0,0,0,0,1,0
E-mail Campaign,4,2,0,0,0,2,1,3,0,0,0
Existing Client,35,0,2,2,1,0,2,0,0,9,0
Existing Customer,13,1,2,0,0,1,2,0,0,3,0
Just Dial,1,9,1,15,2,11,10,5,0,2,0
Live Chat -PPC,11,22,22,39,35,15,38,42,1,24,0
Live Chat-Adwords Remarketing,0,0,1,0,0,2,1,2,0,1,0
Live Chat-Blog,11,27,17,40,26,14,31,54,0,17,0
Live Chat-CPC,1,8,5,13,7,2,4,7,1,2,0
Live Chat-Direct,175,162,192,309,217,102,163,319,9,178,8
Live Chat-Google Ads,3,2,1,5,2,4,1,2,1,0,0
Live Chat-Google Organic,36,22,18,40,27,23,35,38,4,28,3
Live Chat-Justdial,0,0,0,1,0,0,0,0,0,0,0
Live Chat-Quora,0,0,0,0,0,0,0,1,0,1,0
Live Chat-Youtube,0,0,0,0,2,0,0,0,0,0,0
Other,0,0,0,0,0,0,1,1,0,0,0
Personal Contact,17,2,7,6,1,0,4,2,0,11,0
SMS Campaign,1,0,0,0,1,0,0,0,0,0,0
US Website,0,9,0,41,27,4,2,53,1,0,0
Unknown,0,1,0,1,1,1,0,2,10,1,0
Website,143,150,146,283,188,93,125,274,36,150,4

# Observation
The analysis shows the lead outcomes vary across different lead sources. Major sources such as Call,Live Chat-Direct, and Website contribute a substantial number of leads across multiple sales statuses,while smaller sources contribute relatively fewer leads. This indicates that lead souce plays an important role in understanding sales lead distribution and conversion patterns
.

## Sales Agent vs Sales Lead Status

In this step, we will analyze the relationship between Sales Agent and Sales Lead Status. This helps us understand how leads handled by different sales agents are distributed across various outcomes and can reveal diffrences in lead performance among agents.

In [48]:
# Analyzing Sales Agent against Sales Lead Status
pd.crosstab(df['Sales_Agent'], df['Status'])

Status,CONVERTED,In Progress Negative,In Progress Positive,Junk Lead,Just Enquiry,LOST,Long Term,Not Responding,Open,Potential,converted
Sales_Agent,,,,,,,,,,,
Not Available,0,0,0,0,4,0,0,3,14,2,0
Sales-Agent-1,0,0,0,0,0,0,0,0,4,0,0
Sales-Agent-10,0,0,0,5,0,0,0,0,42,0,0
Sales-Agent-11,118,119,8,299,219,40,120,246,1,249,1
Sales-Agent-12,82,51,0,79,0,57,0,0,0,0,0
Sales-Agent-2,61,59,0,94,1,45,111,17,0,1,0
Sales-Agent-3,122,81,36,195,69,47,80,109,1,40,1
Sales-Agent-4,131,91,198,303,193,73,73,293,0,145,0
Sales-Agent-5,77,107,3,318,158,106,92,189,1,138,1
Sales-Agent-6,37,25,0,17,0,11,23,1,0,0,0
Sales-Agent-7,88,64,130,142,52,47,76,112,0,24,1
Sales-Agent-8,2,1,4,11,9,0,2,8,17,1,13
Sales-Agent-9,116,28,264,73,55,14,69,151,0,108,1

# Observation
The analysis shows that lead outcomes vary across sales agents. Some agents handle a substantially higher number of leads across multiple statuses, while others manage fewer leads. This indicates differences in lead volume and status distribution among sales agents.

## Location vs Sales Lead Status

We have already examined the Location distribution separately.

In this step, we will analyze the relationship between customer location and sales lead status to identify diffrences in lead outcomes across locations.

In [49]:
# Analyzing Location against Sales Lead Status
pd.crosstab(df['Location'], df['Status'])

Status,CONVERTED,In Progress Negative,In Progress Positive,Junk Lead,Just Enquiry,LOST,Long Term,Not Responding,Open,Potential,converted
Location,,,,,,,,,,,
AUSTRALIA,5,0,3,3,6,1,0,5,0,2,0
Bangalore,464,159,252,282,95,127,311,150,2,236,6
Chennai,108,85,105,115,91,57,91,100,1,150,6
Delhi,40,75,33,78,64,36,46,53,0,46,0
EUROPE,0,0,1,0,0,0,0,0,0,2,0
Howrah,0,0,0,1,0,0,0,0,0,0,0
Hyderabad,54,62,51,76,69,45,49,70,0,51,1
Kolkata,2,10,3,15,9,2,3,6,0,5,0
Malaysia,3,0,1,0,0,0,0,0,0,0,0
Mumbai,23,56,45,69,56,38,28,41,2,42,2
Not Available,0,0,0,1,3,0,1,4,47,0,0
Other Locations,81,152,123,846,309,123,91,617,24,132,2
Pune,10,18,7,25,19,7,15,28,2,11,0
Singapore,3,1,0,2,3,0,2,2,0,4,0
Trivandrum,6,4,5,8,9,2,4,13,0,6,1
UAE,17,0,7,6,15,1,2,18,1,12,0
UK,12,2,3,4,7,1,1,7,0,4,0
USA,6,2,4,5,5,0,2,15,1,5,0

## Delivery Mode vs Sales Lead Status

In this step, we will analyze the relationship between Delivery Mode and Sales Lead Status to understand how leads handled through different delivery modes are distributed across various outcomes.

In [50]:
# Analyzing Delivery Mode against Sales Lead Status
pd.crosstab(df['Delivery_Mode'],df['Status'])

Status,CONVERTED,In Progress Negative,In Progress Positive,Junk Lead,Just Enquiry,LOST,Long Term,Not Responding,Open,Potential,converted
Delivery_Mode,,,,,,,,,,,
Mode-1,429,274,299,366,154,201,333,295,6,263,7
Mode-2,3,1,2,0,2,1,0,0,1,1,0
Mode-3,165,134,182,257,252,91,139,251,5,206,6
Mode-4,53,8,12,16,3,7,8,5,1,8,0
Mode-5,184,209,148,897,349,140,166,578,67,230,5

# Observation
Mode-5 handles the highest overall volume of leads,while Mode-1 records the highest number of converted leads. This indicates that lead volume and conversion performance vary across diffrent delivery modes.

## Data Preparing for Machine Learning

#### Separating Target and Features

The next step is to prepare the dataset by separating the target variable from the input features. In our Sales Effectiveness project,Status represents the outcome of lead, so it will be our target variable.Before making any transformations, we will create separate variables for the target and features while keeping the original df unchanged.

In [51]:
# Separating the target variable from the feature variables
X = df.drop('Status',axis=1)
Y = df['Status']

print("Features and target variable separated successfully!")

Features and target variable separated successfully!

#### Removing Non-Predictive Identifier and Contact Columns

Some columns in the dataset are identifiers or contact details rather than meaning predictors of sales lead outcomes.Product_ID,Mobile,and Email are not suitable as direct machine-learning features because they do not provide meaningful predictive information. Removing these columns helps the model focus on relevant business-related information while reducing unnecessary complexity.

In [52]:
# Removing identifier and contact information from the features

X = X.drop(['Product_ID', 'Mobile', 'EMAIL'], axis = 1)

print("Non-predictive identifier and contact columns removed successfully!")

Non-predictive identifier and contact columns removed successfully!

### Converting the Date Column into Useful Features

The Created column is already converted to datetime format, but machine-learning models generally work better when dates are represented as meaningful numerical features.Therefore, we will extract the month and day of the week from Created. These features can help the model identify whether lead outcomes vary according to when leads were created. After extracting these useful features, we will remove the orginal Created column from X.

In [53]:
# Extracting useful features from the Created date

X['Created_Month'] = X['Created'].dt.month
X['Created_DayofWeek'] = X['Created'].dt.dayofweek

# Removing the orginal date column
X = X.drop('Created', axis = 1)

print("Date features extracted and orginal Created column removed successfully!")

Date features extracted and orginal Created column removed successfully!

### Encoding Categorical Features

The remaining input features such as Source, Sales_Agent, Location and Delivery_Mode contain categorical values represented as text.
Machine-learning algorithms generally require numerical input, so these categorical features need to be converted into numerical form. We will use One-Hot Encoding, which creates separate binary columns for each category.

In [54]:
# Encoding categorical features using One-Hot Encoding

X = pd.get_dummies(X, columns = ['Source', 'Sales_Agent', 'Location', 'Delivery_Mode'], drop_first =True)

print('Categorical features encoded successfully!')

Categorical features encoded successfully!

## Target Variable Preparation

The original Status column contains several detailed lead outcomes. To match the project objective, these outcomes will be consolidated into two meaningful categories: High Potential and Low Potential. This converts the problem into a binary classification task for the machine-learning model

In [55]:
# Creating Lead Category from Status

status_to_category = {'JUNK LEAD' : 'Low Potential', 'NOT RESPONDING' : 'Low Potential',
                      'JUST ENQUIRY' : 'Low Potential', 'IN PROGRESS NEGATIVE' : 'Low Potential',  'LOST' : 'Low Potential',
                      'CONVERTED' : 'High Potential', 'POTENTIAL' : 'High Potential', 'LONG TERM' : 'High Potential',
                      'IN PROGRESS POSITIVE' : 'High Potential', 'OPEN' : 'High Potential'}

df['Lead_Category'] = (df['Status'].str.upper().str.strip().map(status_to_category))
print('Lead Category created successfully!')

Lead Category created successfully!

In [56]:
df.head()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status,Lead_Category
0,2018-11-14 10:05:00,NaN,Website,984XXXXXXX,aXXXXXXX@gmail.com,Sales-Agent-11,Not Available,Mode-5,Open,High Potential
1,2018-11-14 09:22:00,NaN,Website,XXXXXXX,#VALUE!,Sales-Agent-10,Not Available,Mode-5,Open,High Potential
2,2018-11-14 09:21:00,NaN,Website,XXXXXXX,dXXXXXXX@yahoo.com,Sales-Agent-10,Not Available,Mode-5,Open,High Potential
3,2018-11-14 08:46:00,NaN,Website,XXXXXXX,wXXXXXXX@gmail.com,Sales-Agent-10,Not Available,Mode-5,Open,High Potential
4,2018-11-14 07:34:00,NaN,Website,XXXXXXX,cXXXXXXX@gmail.com,Sales-Agent-10,Not Available,Mode-5,Open,High Potential

In [57]:
df.tail()

,Created,Product_ID,Source,Mobile,EMAIL,Sales_Agent,Location,Delivery_Mode,Status,Lead_Category
7417,2018-04-28 09:45:00,9.0,Call,Not Available,aXXXXXXX@gmail.com,Sales-Agent-6,Mumbai,Mode-4,LOST,Low Potential
7418,2018-04-28 09:43:00,15.0,Call,Not Available,#VALUE!,Sales-Agent-12,Other Locations,Mode-5,LOST,Low Potential
7419,2018-04-28 09:20:00,5.0,Live Chat-Direct,Not Available,sXXXXXXX@gmail.com,Sales-Agent-11,Bangalore,Mode-1,Not Responding,Low Potential
7420,2018-04-28 08:04:00,21.0,CRM form,Not Available,YXXXXXXX@gmail.com,Sales-Agent-4,Other Locations,Mode-1,Just Enquiry,Low Potential
7421,2018-04-28 07:54:00,25.0,Website,Not Available,cXXXXXXX@gmail.com,Sales-Agent-3,Chennai,Mode-1,CONVERTED,High Potential

### Verifying Lead_Category

Before using the target variable for machine learning, we need to verify that every record has been correctly assigned to either High Potential or Low Potential. This quality check ensures that no records were left uncategorized during the mapping process.

In [58]:
# Verifying Lead Category values

print(df['Lead_Category'].value_counts())

print("\nMissing values in Lead_Category :")
print(df['Lead_Category'].isnull().sum())

Lead_Category
Low Potential     4491
High Potential    2929
Name: count, dtype: int64

Missing values in Lead_Category :
0

# Observation
The original sales statuses have been successfully consolidated into two categories: High Potential and Low Potential. The dataset contains 4,491 Low Potential and 2,929 High Potential leads, with no missing values in the newly created Lead_Category variable. this comfirms that the target variable is ready for binary classification model.

## Train-Test Split

The prepared dataset will now be divided into two separate sets: a training set and a testing set. The training set will be used to teach the machine-learning model the patterns in the sales data, while the testing set will be used to evaluate the model on unseen data. We will use an 80:20 split, with 80% of the records for training and 20% of the records for testing. 

The target variable represents the project objective of predicting whether a sales lead is High Potential or Low Potential.

In [59]:
# Preparing the final target variable

Y = df['Lead_Category']

# Splitting the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.20, random_state = 42, stratify = Y)

print("Data successfully split into training and testing sets!")
print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training target shape:", Y_train.shape)
print("Testing target shape:", Y_test.shape)

Data successfully split into training and testing sets!
Training features shape: (5936, 60)
Testing features shape: (1484, 60)
Training target shape: (5936,)
Testing target shape: (1484,)

# Observation
The dataset was successfully divided into training and testing sets using an 80:20 ratio. A Total of 5,936 records are available for model training, while 1,484 records are reserved for evaluating the model on unseen data.

### Target Encoding

The target variable Lead_Category contains two categorical classes: High Potential and Low Potential.Since machine-learning models require numerical target values,Label Encoding is used to convert these categories into numerical labels.

In [60]:
# Encoding the binary target variable

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_test_encoded = label_encoder.transform(Y_test)

print("Target variable encoded successfully!")

Target variable encoded successfully!

In [61]:
# Checking the encoded target classes

print(label_encoder.classes_)

['High Potential' 'Low Potential']

## Machine Learning Model Building

#### Decision Tree Model

A Decision Tree Classifier is used to predict the lead category based on the available lead-related features. The model learns decision rules from the training data and classifies each lead as either High Potential or Low Potential.

In [62]:
# Building the Decision Tree model

from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state = 42)
decision_tree.fit(X_train, Y_train_encoded)

print("Decision Tree model trained successfully!")

Decision Tree model trained successfully!

# Observation
The Decision Tree Classifier was successfully trained using the training dataset. The model is now ready to make prediction on unseen testing data.

### Decision Tree Prediction

The trained Decision Tree model is used to predict the Lead Category for the testing dataset. These prediction will later be compared with the actual target values to evaluate the model's performance.

In [63]:
# Making prediction on the test data

Y_pred = decision_tree.predict(X_test)

print("Prediction generated successfully!")

Prediction generated successfully!

#### Model Evaluation - Accuracy

Accuracy measures the percentage of test records that were classified correctly by the model. It provides an initial understanding of the Decision Tree's performance on unseen data.

In [64]:
# Checking the model accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test_encoded, Y_pred)

print("Decision Tree Accuracy:", accuracy)

Decision Tree Accuracy: 0.6570080862533693

# Observation
The Decision Tree model achieved an accuracy of approximately 65.70% on the test dataset. This provides an initial measure of the model's classification performance on unseen lead data.

#### Decision Tree -Confusion Matrix

A confusion matrix shows how many High Potential and Low Potential leads were classified correctly or incorrectly by the Decision Tree model. It helps us understand the types of predictions made by the model.

In [65]:
# Creating the confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test_encoded, Y_pred)
print(cm)

[[346 240]
 [269 629]]

# Observation
The confusion matrix shows that the Decision Tree correctly classified 346 High Potential leads and 629 Low potential leads. However, 240 High Potential leads and 269 Low Potential leads were misclassified.

#### Classification Report

The classification report is used to evaluate the performance of the Decision Tree model using precision, recall, and F1-score for each lead category.

In [66]:
# Generating the classification report

from sklearn.metrics import classification_report

print(classification_report(Y_test_encoded, Y_pred))

              precision    recall  f1-score   support

           0       0.56      0.59      0.58       586
           1       0.72      0.70      0.71       898

    accuracy                           0.66      1484
   macro avg       0.64      0.65      0.64      1484
weighted avg       0.66      0.66      0.66      1484

# Observation
The Decision Tree achieved an overall accuracy of approximately 66%. The model performed better in identifying Low Potential leads, with an F1-score of 0.71, compared with 0.58 for High Potential leads.

### Random Forest Model

A Random Forest Classifier is used to predict whether a sales lead is High Potential or Low Potential. It combines multiple decision trees to improve prediction performance and reduce the limitations of using a single decision tree.

In [67]:
# Building the Random Forest model

from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(random_state = 42)

random_forest.fit(X_train, Y_train_encoded)
print("Random Forest model trained successfully!")

Random Forest model trained successfully!

#### Random Forest Prediction

The trained Random Forest model is used to predict the Lead Category for the testing dataset. These predictions will be used to evaluate how well the model performs on unseen data.

In [68]:
# Making predictions with Random Forest

Y_pred_rf = random_forest.predict(X_test)

print("Random Forest predictions generated successfully!")

Random Forest predictions generated successfully!

#### Random Forest Accuracy

Accuracy is used to measure the proportion of test records that were correctly classified by the Random Forest model.

In [69]:
# Checking Random Forest accuracy

accuracy_rf = accuracy_score(Y_test_encoded, Y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)

Random Forest Accuracy: 0.681266846361186

# Observation
The Random Forest model achieved an accuracy of approximately 68% on the test dataset. It shows a slight improvement over the Decision Tree model, which achieved an accuracy of approximately 65.70%.

#### Random Forest- Confusion Matrix

The confusion matrix is used to examine the correct and incorrect predictions made by the Random Forest model for High Potential and Low Potential Leads.

In [70]:
# Creating the Random forest confusion matrix

cm_rf = confusion_matrix(Y_test_encoded, Y_pred_rf)
print(cm_rf)

[[322 264]
 [209 689]]

# Observation
The Confusion Matrix shows that the Random Forest correctly classified 322 High Potential leads and 689 Low Potential leads. The model misclassified 264 High Potential leads and 209 Low Potential leads.

#### Classification Report

The classification report evaluates the Random Forest model using precision, recall, and F1-score for High Potential and Low Potential.

In [71]:
# Generating the Random Forest classification report

print(classification_report(Y_test_encoded,Y_pred_rf))

              precision    recall  f1-score   support

           0       0.61      0.55      0.58       586
           1       0.72      0.77      0.74       898

    accuracy                           0.68      1484
   macro avg       0.66      0.66      0.66      1484
weighted avg       0.68      0.68      0.68      1484

# Observation
The Random Forest model achieved an accuracy of approximately 68%. The model performed better in identifying Low Potential leads, with an F1-score of 0.74,while the F1-score for High Potential leads was 0.58. Overall, Random Forest shows a slight improvement over the Decision Tree model.

### Logistic Regression

Logistic Regression is a classification algorithm used to predict whether a sales lead belongs to the High Potential or Low Potential category.

In [72]:
# Building the Logistic Regression model

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(max_iter = 1000, random_state = 42)
logistic_model.fit(X_train,Y_train_encoded)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

#### Logistic Regression Prediction

The trained Logistic Regression model is used to predict the Lead Category for testing dataset. These predictions will be used to evaluate the model on unseen data.

In [73]:
# Making prediction with Logistic Regression

Y_pred_lr = logistic_model.predict(X_test)

print("Logistic Regression predictions generated successfully!")

Logistic Regression predictions generated successfully!

#### Logistic Regression Accuracy

This step checks how accurately the Logistic Regression model predicted the High Potential and Low Potential lead categories on the test data.

In [74]:
# Checking Logistic Regression accuracy

accuracy_lr = accuracy_score(Y_test_encoded, Y_pred_lr)

print("Logistic Regression Accuracy:", accuracy_lr)

Logistic Regression Accuracy: 0.7196765498652291

#### Logistic Regression - Confusion Matrix

The confusion matrix shows how many High Potential and Low Potential leads were classified correctly or incorrectly by the Logistic Regression model.

In [75]:
# Creating the confusion matrix for Logistic Regression

cm_lr = confusion_matrix(Y_test_encoded, Y_pred_lr)

print(cm_lr)

[[320 266]
 [150 748]]

#### Classification Report

Now we'll calculate Precision, Recall, and F1-score for both categories.

In [76]:
# Generating the classifiaction report for Logistic Regression

print(classification_report(Y_test_encoded, Y_pred_lr, target_names = label_encoder.classes_))

                precision    recall  f1-score   support

High Potential       0.68      0.55      0.61       586
 Low Potential       0.74      0.83      0.78       898

      accuracy                           0.72      1484
     macro avg       0.71      0.69      0.69      1484
  weighted avg       0.72      0.72      0.71      1484

# Observation
The Logistic Regression model achieved an overall accuracy of approximately 72%. The model performed better in identifying Low Potential leads, with F1-score of 0.78, compared with 0.61 for High Potential leads. Overall, Logistic Regression shows better performance than the Decision Tree and Random Forest models based on accuracy.

## Model Comparison

In this step, we will compare the performance of the three models using their evaluation results. This helps us identify which model performed best on the test data.

In [77]:
# Comparing the accuracy of all three models

print("Decision Tree Accuracy :", accuracy)
print("Random Forest Accuracy :", accuracy_rf)
print("Logistic Regression :", accuracy_lr)

Decision Tree Accuracy : 0.6570080862533693
Random Forest Accuracy : 0.681266846361186
Logistic Regression : 0.7196765498652291

# Observation
Among the three classification models, Logistic Regression achieved the highest accuracy of approximately 71.97%, followed by Random Forest with 68.13% and Decision Tree with 65.70%. Therefore, Logistic Regression is selected as the best-performing model among the tested models for predicting High Potential and Low Potential.

### Creating Model Comparison Table

In [78]:
# Creating a comparison table for three models

model_comparison = pd.DataFrame({'Model': ['Decision Tree', 'Random Forest', 'Logistic Regression'], 'Accuracy': [accuracy, accuracy_rf, accuracy_lr]})

display(model_comparison)

                 Model  Accuracy
0        Decision Tree  0.657008
1        Random Forest  0.681267
2  Logistic Regression  0.719677

## Feature Importance

In this step,we identify which features are most influential in predicting High potential vs Low Potential leads.

In [79]:
# Extracting feature importance from Logistic Refression

feature_importance = pd.DataFrame({'Feature': X_train.columns, 'Coefficient': logistic_model.coef_[0]})

feature_importance['Absolute_Coefficient'] = feature_importance['Coefficient'].abs()

feature_importance = feature_importance.sort_values(by = 'Absolute_Coefficient', ascending = False)

display(feature_importance.head(10))

                       Feature  Coefficient  Absolute_Coefficient
24           Source_US Website     2.328289              2.328289
48      Location_Not Available    -2.045112              2.045112
8       Source_Existing Client    -1.852896              1.852896
10            Source_Just Dial     1.535951              1.535951
5     Source_Customer Referral    -1.474581              1.474581
30  Sales_Agent_Sales-Agent-12     1.335412              1.335412
46           Location_Malaysia    -1.102769              1.102769
32   Sales_Agent_Sales-Agent-3     1.093532              1.093532
14        Source_Live Chat-CPC     1.050089              1.050089
49    Location_Other Locations     1.030939              1.030939

# Observation
The Logistic Regression coefficient show that several lead sources, locations, and sales agents have a strong influence on the prediction of the lead potential. Source_US Website has the strongest positive coefficient, while Location_Not_Available and Source_Existing Client also show strong influence.
These results indicate that lead source, Location, and sales-agent information are important factors in predicting whether a lead is High Potential or Low Potential.

## Business Insights & Recommendations

### Business Insights

1. The dataset contains more Low Potential leads than high potential leads, indicating that a significant portion of leads may require better qualification.

2. Call, Live Chat-Direct, and Website are the major lead sources and contribute a large share of the overall leads.

3. Lead outcomes vary across sales agents, indicating diffreces in lead distribution and sales performance.

4. Logistic Rergression achieved the highest accuracy of 71.97% among the tested models, making it the best-performing model for predicting High Potential and Low Potential.

### Business Recommendations

1. Give more attention to High Potential leads to improve the chances of conversion.

2. Focus on the major lead sources and identify which sources are giving better-quality leads.

3. Improve lead distribution among sales agents so that the workload is balanced and sales performance can be improved.

4. Analyze different locations and delivery modes to identify where better sales results are achieved.

5. Use the Logistic Regression model to help the sales team identify and prioritize High Potential leads.

## Final Conclusion

The Sales Effectiveness project was completed by analyzing and preprocessing the sales lead data to understand lead sources, sales agents, locations, delivery modes, and lead outcomes. The original lead statuses were converted into two categories: High Potential and Low Potential for machine learning.


Three classification models were developed and evaluated: Decision Tree, Random Forest, and Logistic Regression. Logistic Regression achieved the highest accuracy of approximately 71.97%, making it the best-performing model for predicting lead potential.


The analysis and model results can help the sales team identify and prioritize High Potential leads, improve lead allocation, and understand factors that influence sales effectiveness.